.SUFFIXES: .cpp .o

CXX=g++
TARGET=a.out
OBJS=main.o

ifneq (${TPARTY_HOME}, "")
CXXFLAGS=-I${TPARTY_HOME}/local/include
LDFLAGS=-L${TPARTY_HOME}/local/lib
endif

CXXFLAGS+=-Wall -std=c++11
LDFLAGS+=-lpthread -luv

.PONEY=all clean

all: ${TARGET}

clean:
	rm -rf ${OBJS} ${TARGET}

${TARGET}: ${OBJS}
	${CXX} -o $@ ${LDFLAGS} $^

